services:
    backend_prod:
        build:
            context: .
            dockerfile: ./config/prod/Dockerfile
        expose:
            - 80:80
        ports:
            - 8080:80
        depends_on:
            - database
        environment:
            - SECRET_KEY=DEVKEY
            - EMAIL_HOST=mail
            - ALLOWED_HOSTS=app.localtest.me;localhost

    nginx:
        image: nginx:latest
        command: /dev-config/nginx-startup.sh
        volumes:
            - "./config/dev/nginx/nginx-tlswrapper.conf:/etc/nginx/conf.d/default.conf:z,ro"
            # If you volume mount files that don't exist, docker will create
            # a folder on the host automatically. So bind in the whole
            # directory
            - "./config/dev/nginx/:/dev-config/:z,ro"
        ports:
            - 443:443
            - 80:80
        links:
            - backend_prod

    database:
        image: postgres:latest
        environment:
            - POSTGRES_PASSWORD=password
        ports:
            - target: 5432
              published: 5432
        healthcheck:
            test: ["CMD-SHELL", "sh -c 'pg_isready -U postgres -d postgres'"]
            interval: 10s
            timeout: 3s
            retries: 3

    mail:
        image: djfarrelly/maildev
        # Explicit command is so nginx can proxy to it on the /maildev path
        command: bin/maildev --web 80 --smtp 25 --base-pathname /maildev
